# Generated by Django 4.2.16 on 2024-11-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('organizador', 'Organizador de Eventos'), ('profissional', 'Profissional de Eventos'), ('comum', 'Usuário Comum')], default='comum', max_length=15, verbose_name='Tipo de Usuário'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone'),
        ),
    ]
