# Generated by Django 4.2.16 on 2024-11-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_eventos_app', '0002_customuser_user_type_alter_customuser_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Usuário Liberado'),
        ),
    ]
